// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WSRS_Formators.Data;

#nullable disable

namespace WSRS_Formators.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20250411131557_9-15pm-4-11-2025")]
    partial class _915pm4112025
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WSRS_Formators.Models.College", b =>
                {
                    b.Property<string>("CollegeID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CollegeID");

                    b.ToTable("Colleges");
                });

            modelBuilder.Entity("WSRS_Formators.Models.Offense", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Classification")
                        .HasColumnType("int");

                    b.Property<string>("Nature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Offenses");
                });

            modelBuilder.Entity("WSRS_Formators.Models.ReportEncoded", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CollegeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("CommissionDate")
                        .HasColumnType("date");

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("HearingDate")
                        .HasColumnType("date");

                    b.Property<int>("OffenseId")
                        .HasColumnType("int");

                    b.Property<string>("Sanction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusOfSanction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CollegeID");

                    b.HasIndex("OffenseId");

                    b.HasIndex("StudentNumber");

                    b.ToTable("ReportsEncoded");
                });

            modelBuilder.Entity("WSRS_Formators.Models.ReportPending", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CommissionDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentNumber");

                    b.ToTable("ReportsPending");
                });

            modelBuilder.Entity("WSRS_Formators.Models.ReportViolation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("College")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("CommissionDate")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ReportsViolation");
                });

            modelBuilder.Entity("WSRS_Formators.Models.Student", b =>
                {
                    b.Property<int>("StudentNumber")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentNumber");

                    b.HasIndex("StudentNumber");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("WSRS_Formators.Models.TrafficReportsEncoded", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CollegeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("CommissionDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DatePaid")
                        .HasColumnType("date");

                    b.Property<string>("ORNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OffenseId")
                        .HasColumnType("int");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CollegeID");

                    b.HasIndex("OffenseId");

                    b.HasIndex("StudentNumber");

                    b.ToTable("TrafficReportsEncoded");
                });

            modelBuilder.Entity("WSRS_Formators.Models.ReportEncoded", b =>
                {
                    b.HasOne("WSRS_Formators.Models.College", "College")
                        .WithMany()
                        .HasForeignKey("CollegeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WSRS_Formators.Models.Offense", "Offense")
                        .WithMany()
                        .HasForeignKey("OffenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WSRS_Formators.Models.Student", "Student")
                        .WithMany("ReportsEncoded")
                        .HasForeignKey("StudentNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("College");

                    b.Navigation("Offense");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("WSRS_Formators.Models.ReportPending", b =>
                {
                    b.HasOne("WSRS_Formators.Models.Student", "Student")
                        .WithMany("ReportsPending")
                        .HasForeignKey("StudentNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("WSRS_Formators.Models.TrafficReportsEncoded", b =>
                {
                    b.HasOne("WSRS_Formators.Models.College", "College")
                        .WithMany()
                        .HasForeignKey("CollegeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WSRS_Formators.Models.Offense", "Offense")
                        .WithMany()
                        .HasForeignKey("OffenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WSRS_Formators.Models.Student", "Student")
                        .WithMany("TrafficReportsEncoded")
                        .HasForeignKey("StudentNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("College");

                    b.Navigation("Offense");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("WSRS_Formators.Models.Student", b =>
                {
                    b.Navigation("ReportsEncoded");

                    b.Navigation("ReportsPending");

                    b.Navigation("TrafficReportsEncoded");
                });
#pragma warning restore 612, 618
        }
    }
}
