<<<<<<< HEAD
=======
<<<<<<<< HEAD:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
﻿// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
using WSRS_Student.Data;

#nullable disable

namespace WSRS_Student.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250401055242_IdentitySetup")]
    partial class IdentitySetup
========
using WSRS_SWAFO.Data;

#nullable disable

namespace WSRS_SWAFO.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250501103848_RemoveHearingDateInEncoded")]
    partial class RemoveHearingDateInEncoded
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
========
            modelBuilder.Entity("HearingSchedules", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentNumber")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StudentNumber");

                    b.ToTable("HearingSchedules");
                });

>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");
========
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");
========
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
            modelBuilder.Entity("WSRS_Student.Models.ApplicationUser", b =>
========
            modelBuilder.Entity("WSRS_SWAFO.Models.ApplicationUser", b =>
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
========
                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
========
                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
            modelBuilder.Entity("WSRS_Student.Models.College", b =>
========
            modelBuilder.Entity("WSRS_SWAFO.Models.College", b =>
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
                {
                    b.Property<string>("CollegeID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CollegeID");

<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
                    b.ToTable("Colleges");
                });

            modelBuilder.Entity("WSRS_Student.Models.Offense", b =>
========
                    b.ToTable("College");
                });

            modelBuilder.Entity("WSRS_SWAFO.Models.Offense", b =>
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Classification")
                        .HasColumnType("int");

                    b.Property<string>("Nature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Offenses");
                });

<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
            modelBuilder.Entity("WSRS_Student.Models.ReportEncoded", b =>
========
            modelBuilder.Entity("WSRS_SWAFO.Models.ReportEncoded", b =>
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CollegeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("CommissionDate")
                        .HasColumnType("date");

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
                    b.Property<DateOnly?>("HearingDate")
                        .HasColumnType("date");
========
                    b.Property<string>("Formator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormatorId")
                        .HasColumnType("nvarchar(max)");
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs

                    b.Property<int>("OffenseId")
                        .HasColumnType("int");

                    b.Property<string>("Sanction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusOfSanction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CollegeID");

                    b.HasIndex("OffenseId");

                    b.HasIndex("StudentNumber");

                    b.ToTable("ReportsEncoded");
                });

<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
            modelBuilder.Entity("WSRS_Student.Models.ReportPending", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CommissionDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentNumber");

                    b.ToTable("ReportsPending");
                });

            modelBuilder.Entity("WSRS_Student.Models.Student", b =>
========
            modelBuilder.Entity("WSRS_SWAFO.Models.Student", b =>
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
                {
                    b.Property<int>("StudentNumber")
                        .HasColumnType("int");

<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
========
                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentNumber");

                    b.HasIndex("StudentNumber");

                    b.ToTable("Students");
                });

<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
            modelBuilder.Entity("WSRS_Student.Models.TrafficReportsEncoded", b =>
========
            modelBuilder.Entity("WSRS_SWAFO.Models.TrafficReportsEncoded", b =>
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CollegeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("CommissionDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DatePaid")
                        .HasColumnType("date");

                    b.Property<string>("ORNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OffenseId")
                        .HasColumnType("int");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CollegeID");

                    b.HasIndex("OffenseId");

                    b.HasIndex("StudentNumber");

                    b.ToTable("TrafficReportsEncoded");
                });

<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
========
            modelBuilder.Entity("HearingSchedules", b =>
                {
                    b.HasOne("WSRS_SWAFO.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
                    b.HasOne("WSRS_Student.Models.ApplicationUser", null)
========
                    b.HasOne("WSRS_SWAFO.Models.ApplicationUser", null)
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
                    b.HasOne("WSRS_Student.Models.ApplicationUser", null)
========
                    b.HasOne("WSRS_SWAFO.Models.ApplicationUser", null)
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
                    b.HasOne("WSRS_Student.Models.ApplicationUser", null)
========
                    b.HasOne("WSRS_SWAFO.Models.ApplicationUser", null)
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
                    b.HasOne("WSRS_Student.Models.ApplicationUser", null)
========
                    b.HasOne("WSRS_SWAFO.Models.ApplicationUser", null)
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
            modelBuilder.Entity("WSRS_Student.Models.ReportEncoded", b =>
                {
                    b.HasOne("WSRS_Student.Models.College", "College")
========
            modelBuilder.Entity("WSRS_SWAFO.Models.ReportEncoded", b =>
                {
                    b.HasOne("WSRS_SWAFO.Models.College", "College")
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
                        .WithMany()
                        .HasForeignKey("CollegeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
                    b.HasOne("WSRS_Student.Models.Offense", "Offense")
========
                    b.HasOne("WSRS_SWAFO.Models.Offense", "Offense")
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
                        .WithMany()
                        .HasForeignKey("OffenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
                    b.HasOne("WSRS_Student.Models.Student", "Student")
========
                    b.HasOne("WSRS_SWAFO.Models.Student", "Student")
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
                        .WithMany("ReportsEncoded")
                        .HasForeignKey("StudentNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("College");

                    b.Navigation("Offense");

                    b.Navigation("Student");
                });

<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
            modelBuilder.Entity("WSRS_Student.Models.ReportPending", b =>
                {
                    b.HasOne("WSRS_Student.Models.Student", "Student")
                        .WithMany("ReportsPending")
                        .HasForeignKey("StudentNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("WSRS_Student.Models.TrafficReportsEncoded", b =>
                {
                    b.HasOne("WSRS_Student.Models.College", "College")
========
            modelBuilder.Entity("WSRS_SWAFO.Models.TrafficReportsEncoded", b =>
                {
                    b.HasOne("WSRS_SWAFO.Models.College", "College")
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
                        .WithMany()
                        .HasForeignKey("CollegeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
                    b.HasOne("WSRS_Student.Models.Offense", "Offense")
========
                    b.HasOne("WSRS_SWAFO.Models.Offense", "Offense")
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
                        .WithMany()
                        .HasForeignKey("OffenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
                    b.HasOne("WSRS_Student.Models.Student", "Student")
========
                    b.HasOne("WSRS_SWAFO.Models.Student", "Student")
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
                        .WithMany("TrafficReportsEncoded")
                        .HasForeignKey("StudentNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("College");

                    b.Navigation("Offense");

                    b.Navigation("Student");
                });

<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
            modelBuilder.Entity("WSRS_Student.Models.Student", b =>
                {
                    b.Navigation("ReportsEncoded");

                    b.Navigation("ReportsPending");

========
            modelBuilder.Entity("WSRS_SWAFO.Models.Student", b =>
                {
                    b.Navigation("ReportsEncoded");

>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
                    b.Navigation("TrafficReportsEncoded");
                });
#pragma warning restore 612, 618
        }
    }
}
========
>>>>>>> f9dae977f1534b7b731ff04adffb927b1827cdb6
﻿// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
<<<<<<< HEAD
<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
=======
>>>>>>> f9dae977f1534b7b731ff04adffb927b1827cdb6
using WSRS_Student.Data;

#nullable disable

namespace WSRS_Student.Migrations
{
<<<<<<< HEAD
<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250401055242_IdentitySetup")]
    partial class IdentitySetup
========
using WSRS_SWAFO.Data;

#nullable disable

namespace WSRS_SWAFO.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250501103848_RemoveHearingDateInEncoded")]
    partial class RemoveHearingDateInEncoded
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
=======
    [DbContext(typeof(AuthDbContext))]
    [Migration("20250502023811_InitialCreate")]
    partial class InitialCreate
>>>>>>> c833464 (feat: add new migration for authentication):WSRS-Student/Migrations/20250502023811_InitialCreate.Designer.cs
=======
    [DbContext(typeof(AuthDbContext))]
    [Migration("20250502023811_InitialCreate")]
    partial class InitialCreate
>>>>>>> f9dae977f1534b7b731ff04adffb927b1827cdb6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

<<<<<<< HEAD
<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
========
            modelBuilder.Entity("HearingSchedules", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentNumber")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StudentNumber");

                    b.ToTable("HearingSchedules");
                });

>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
=======
>>>>>>> f9dae977f1534b7b731ff04adffb927b1827cdb6
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", "Student");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "Student");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "Student");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
<<<<<<< HEAD
<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
=======
>>>>>>> f9dae977f1534b7b731ff04adffb927b1827cdb6
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");
<<<<<<< HEAD
========
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
=======
>>>>>>> f9dae977f1534b7b731ff04adffb927b1827cdb6

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "Student");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "Student");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
<<<<<<< HEAD
<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
=======
>>>>>>> f9dae977f1534b7b731ff04adffb927b1827cdb6
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");
<<<<<<< HEAD
========
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
=======
>>>>>>> f9dae977f1534b7b731ff04adffb927b1827cdb6

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "Student");
                });

<<<<<<< HEAD
<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
            modelBuilder.Entity("WSRS_Student.Models.ApplicationUser", b =>
========
            modelBuilder.Entity("WSRS_SWAFO.Models.ApplicationUser", b =>
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
=======
            modelBuilder.Entity("WSRS_Student.Models.ApplicationUser", b =>
>>>>>>> f9dae977f1534b7b731ff04adffb927b1827cdb6
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

<<<<<<< HEAD
<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
========
                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
=======
                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
>>>>>>> f9dae977f1534b7b731ff04adffb927b1827cdb6

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

<<<<<<< HEAD
<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
========
                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
=======
                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
>>>>>>> f9dae977f1534b7b731ff04adffb927b1827cdb6

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

<<<<<<< HEAD
<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
                    b.ToTable("AspNetUsers", (string)null);
                });

<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
            modelBuilder.Entity("WSRS_Student.Models.College", b =>
========
            modelBuilder.Entity("WSRS_SWAFO.Models.College", b =>
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
                {
                    b.Property<string>("CollegeID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CollegeID");

<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
                    b.ToTable("Colleges");
                });

            modelBuilder.Entity("WSRS_Student.Models.Offense", b =>
========
                    b.ToTable("College");
                });

            modelBuilder.Entity("WSRS_SWAFO.Models.Offense", b =>
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Classification")
                        .HasColumnType("int");

                    b.Property<string>("Nature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Offenses");
                });

<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
            modelBuilder.Entity("WSRS_Student.Models.ReportEncoded", b =>
========
            modelBuilder.Entity("WSRS_SWAFO.Models.ReportEncoded", b =>
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CollegeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("CommissionDate")
                        .HasColumnType("date");

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
                    b.Property<DateOnly?>("HearingDate")
                        .HasColumnType("date");
========
                    b.Property<string>("Formator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormatorId")
                        .HasColumnType("nvarchar(max)");
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs

                    b.Property<int>("OffenseId")
                        .HasColumnType("int");

                    b.Property<string>("Sanction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusOfSanction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CollegeID");

                    b.HasIndex("OffenseId");

                    b.HasIndex("StudentNumber");

                    b.ToTable("ReportsEncoded");
                });

<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
            modelBuilder.Entity("WSRS_Student.Models.ReportPending", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CommissionDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentNumber");

                    b.ToTable("ReportsPending");
                });

            modelBuilder.Entity("WSRS_Student.Models.Student", b =>
========
            modelBuilder.Entity("WSRS_SWAFO.Models.Student", b =>
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
                {
                    b.Property<int>("StudentNumber")
                        .HasColumnType("int");

<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
========
                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentNumber");

                    b.HasIndex("StudentNumber");

                    b.ToTable("Students");
                });

<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
            modelBuilder.Entity("WSRS_Student.Models.TrafficReportsEncoded", b =>
========
            modelBuilder.Entity("WSRS_SWAFO.Models.TrafficReportsEncoded", b =>
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CollegeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("CommissionDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DatePaid")
                        .HasColumnType("date");

                    b.Property<string>("ORNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OffenseId")
                        .HasColumnType("int");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CollegeID");

                    b.HasIndex("OffenseId");

                    b.HasIndex("StudentNumber");

                    b.ToTable("TrafficReportsEncoded");
=======
                    b.ToTable("AspNetUsers", "Student");
>>>>>>> c833464 (feat: add new migration for authentication):WSRS-Student/Migrations/20250502023811_InitialCreate.Designer.cs
                });

<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
========
            modelBuilder.Entity("HearingSchedules", b =>
                {
                    b.HasOne("WSRS_SWAFO.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
=======
                    b.ToTable("AspNetUsers", "Student");
                });

>>>>>>> f9dae977f1534b7b731ff04adffb927b1827cdb6
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
<<<<<<< HEAD
<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
                    b.HasOne("WSRS_Student.Models.ApplicationUser", null)
========
                    b.HasOne("WSRS_SWAFO.Models.ApplicationUser", null)
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
=======
                    b.HasOne("WSRS_Student.Models.ApplicationUser", null)
>>>>>>> f9dae977f1534b7b731ff04adffb927b1827cdb6
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
<<<<<<< HEAD
<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
                    b.HasOne("WSRS_Student.Models.ApplicationUser", null)
========
                    b.HasOne("WSRS_SWAFO.Models.ApplicationUser", null)
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
=======
                    b.HasOne("WSRS_Student.Models.ApplicationUser", null)
>>>>>>> f9dae977f1534b7b731ff04adffb927b1827cdb6
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

<<<<<<< HEAD
<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
                    b.HasOne("WSRS_Student.Models.ApplicationUser", null)
========
                    b.HasOne("WSRS_SWAFO.Models.ApplicationUser", null)
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
=======
                    b.HasOne("WSRS_Student.Models.ApplicationUser", null)
>>>>>>> f9dae977f1534b7b731ff04adffb927b1827cdb6
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
<<<<<<< HEAD
<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
                    b.HasOne("WSRS_Student.Models.ApplicationUser", null)
========
                    b.HasOne("WSRS_SWAFO.Models.ApplicationUser", null)
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
=======
                    b.HasOne("WSRS_Student.Models.ApplicationUser", null)
>>>>>>> f9dae977f1534b7b731ff04adffb927b1827cdb6
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
<<<<<<< HEAD
<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs

<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
            modelBuilder.Entity("WSRS_Student.Models.ReportEncoded", b =>
                {
                    b.HasOne("WSRS_Student.Models.College", "College")
========
            modelBuilder.Entity("WSRS_SWAFO.Models.ReportEncoded", b =>
                {
                    b.HasOne("WSRS_SWAFO.Models.College", "College")
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
                        .WithMany()
                        .HasForeignKey("CollegeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
                    b.HasOne("WSRS_Student.Models.Offense", "Offense")
========
                    b.HasOne("WSRS_SWAFO.Models.Offense", "Offense")
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
                        .WithMany()
                        .HasForeignKey("OffenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
                    b.HasOne("WSRS_Student.Models.Student", "Student")
========
                    b.HasOne("WSRS_SWAFO.Models.Student", "Student")
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
                        .WithMany("ReportsEncoded")
                        .HasForeignKey("StudentNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("College");

                    b.Navigation("Offense");

                    b.Navigation("Student");
                });

<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
            modelBuilder.Entity("WSRS_Student.Models.ReportPending", b =>
                {
                    b.HasOne("WSRS_Student.Models.Student", "Student")
                        .WithMany("ReportsPending")
                        .HasForeignKey("StudentNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("WSRS_Student.Models.TrafficReportsEncoded", b =>
                {
                    b.HasOne("WSRS_Student.Models.College", "College")
========
            modelBuilder.Entity("WSRS_SWAFO.Models.TrafficReportsEncoded", b =>
                {
                    b.HasOne("WSRS_SWAFO.Models.College", "College")
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
                        .WithMany()
                        .HasForeignKey("CollegeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
                    b.HasOne("WSRS_Student.Models.Offense", "Offense")
========
                    b.HasOne("WSRS_SWAFO.Models.Offense", "Offense")
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
                        .WithMany()
                        .HasForeignKey("OffenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
                    b.HasOne("WSRS_Student.Models.Student", "Student")
========
                    b.HasOne("WSRS_SWAFO.Models.Student", "Student")
>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
                        .WithMany("TrafficReportsEncoded")
                        .HasForeignKey("StudentNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("College");

                    b.Navigation("Offense");

                    b.Navigation("Student");
                });

<<<<<<<< HEAD:WSRS-Student/Migrations/20250401055242_IdentitySetup.Designer.cs
            modelBuilder.Entity("WSRS_Student.Models.Student", b =>
                {
                    b.Navigation("ReportsEncoded");

                    b.Navigation("ReportsPending");

========
            modelBuilder.Entity("WSRS_SWAFO.Models.Student", b =>
                {
                    b.Navigation("ReportsEncoded");

>>>>>>>> main:WSRS-Student/Migrations/20250501103848_RemoveHearingDateInEncoded.Designer.cs
                    b.Navigation("TrafficReportsEncoded");
                });
=======
>>>>>>> c833464 (feat: add new migration for authentication):WSRS-Student/Migrations/20250502023811_InitialCreate.Designer.cs
=======
>>>>>>> f9dae977f1534b7b731ff04adffb927b1827cdb6
#pragma warning restore 612, 618
        }
    }
}
<<<<<<< HEAD
=======
>>>>>>>> f9dae977f1534b7b731ff04adffb927b1827cdb6:WSRS-Student/Migrations/20250502023811_InitialCreate.Designer.cs
>>>>>>> f9dae977f1534b7b731ff04adffb927b1827cdb6
